# Generated by Django 2.1.2 on 2018-10-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181015_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalatempo',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempo', to='core.Turno'),
        ),
    ]
