# Generated by Django 2.1.2 on 2018-10-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_diaagenda_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalatempo',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
