# Generated by Django 2.1.2 on 2018-10-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_escalatempo_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='escala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.EscalaTempo'),
            preserve_default=False,
        ),
    ]
