# Generated by Django 2.1.2 on 2018-10-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_consulta_escala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='escala',
        ),
        migrations.AddField(
            model_name='consulta',
            name='fim',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='inicio',
            field=models.TimeField(null=True),
        ),
    ]
