# Generated by Django 2.1.2 on 2018-10-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181017_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
