# Generated by Django 2.1.2 on 2018-10-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_consulta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
