# Generated by Django 2.1.2 on 2018-10-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_especialidade_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fim',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
