# Generated by Django 2.1.2 on 2018-10-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181018_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
