# Generated by Django 2.1.2 on 2018-10-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_turno_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escalatempo',
            old_name='dia',
            new_name='turno',
        ),
    ]
