# Generated by Django 2.1.2 on 2018-10-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181023_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaagenda',
            name='turnos',
        ),
        migrations.AddField(
            model_name='turno',
            name='dia_agenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.DiaAgenda'),
            preserve_default=False,
        ),
    ]
