# Generated by Django 2.1.2 on 2018-10-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181023_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='convenio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='convenio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.Convenio'),
            preserve_default=False,
        ),
    ]
