# Generated by Django 2.1.2 on 2018-11-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181024_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº CPF'),
        ),
    ]
